import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './components/NavBar'
import SideBar from './components/SideBar'
import { CartProvider } from './contexts/cartContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'KCF E-Commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <div>
            <SideBar />           
            <div>
              <NavBar />
              {children}
            </div>        
          </div>
        </CartProvider>
      </body>
    </html>
  )
}
